### ISSUE TITLE
insert_returning from asyncpg driver doesn't let you use record_class

### ISSUE THREAD

**Issue by euri10** [nackjicholson/aiosql#10]
is that intended ?

could use the same pattern:
```
            if result is not None and record_class is not None:
                result = record_class(**dict(result))
``` 
after https://github.com/nackjicholson/aiosql/blob/cf6289c4d3395db5027e64ec845cc5a3918077f8/aiosql/adapters/asyncpg.py#L102

let me know if you think it's worth it

**Comment by nackjicholson** [comment]
Hello, thanks for the question! It looks like none of the adapters use `record_class` in their `insert_returning` methods. Was it intentional? Yes. But maybe it's more accurate to say I just haven't personally seen the need in my work to have the `record_class` be available for anything except `select` and `select_one`.

Do you have an example of a query where you'll be wanting to use an insert/return where the return is something you'd want to build a record class for?

**Comment by euri10** [comment]
somehting like that happened to me
```
-- name: insert_or_get_topic_id^
insert into subscriber.topics (url)
values (:url)
on conflict (url) do update set last_time_accessed=now()
returning id;
```

**Comment by euri10** [comment]
@nackjicholson I added a test that shows usage and fixed the issue in https://github.com/euri10/aiosql/tree/returning

please let me know if you think this has any chance to get merged, I find it quite useful since I'm using a lot inserts with returning clauses :)

should you want it I'll PR it either on the above branch either rebased on master

**Comment by zx80** [comment]
I'm unclear about this one. An  `INSERT RETURNING` behaves like a `SELECT` because it returns a relation.

Why not use  `select`, `select_one` or `select_value` code path instead of inventing a new one?
