### ISSUE TITLE
`'UUID' object has no attribute 'replace'` when using UUID column with `psycopg` driver

### ISSUE THREAD

**Issue by NOBLES5E** [nackjicholson/aiosql#142]

**Comment by NOBLES5E** [comment]
Turns out when returning an UUID,  with`psycho2` driver it returns a string while with `psycho` driver it returns an UUID class. Not sure if this is intended. Feel free to close.

**Comment by zx80** [comment]
Indeed, `aiosql` just wraps the queries, but the result are still what the driver does, and I do not feel it should be its place to work around that. The module just returns what the driver returned.

According to [psycopg2 documentation](https://www.psycopg.org/docs/usage.html#adaptation-of-python-values-to-sql-types) the UUID type should be mapped to uuid, though. Maybe you could check with your query using a direct `psycopg2` connection if the problem is the same, and possibly report the issue to psycopg? Or use only psycopg 3?
