### ISSUE TITLE
How to support mysql

### ISSUE THREAD

**Issue by sylvoslee** [nackjicholson/aiosql#24]
How to support mysql

**Comment by nackjicholson** [comment]
Good Question! I may actually have a need to solve that soon as well. I was looking at [this driver](https://mariadb-corporation.github.io/mariadb-connector-python/usage.html#connecting) as a possibility.

There is a section in the documentation about how you can extend aiosql to support other types of database drivers. Look at the implementation of the ones that are built in to get an idea of how that works. https://github.com/nackjicholson/aiosql/tree/master/aiosql/adapters Unfortunately, the answer is you have to write an adapter yourself because only SQLite and PostgreSQL are supported by built-in drivers. I am not aware of an async driver for MySQL/MariaDB. Let me know if you know of one.

**Comment by sylvoslee** [comment]
async driver for MySQL:[https://github.com/aio-libs/aiomysql](url)，but the performance is not good

sync driver for MySQL:[https://github.com/PyMySQL/mysqlclient-python](url)

**Comment by nackjicholson** [comment]
Thanks for the info. Let me know if you make your own MySQL/MariaDB adapter. I'll do the same if I make one.
